name: Deploy from Main

on:
  push:
    branches:
      - main
      - feature/**
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (adjust for your stack if needed)
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/main'  # Only deploy if build passes and on main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: echo "deploying from 'main' branch"  # Replace with your actual deployment command

  required-status-checks:
    runs-on: ubuntu-latest
    needs: build
    if: success()  # This job only runs if the build job was successful
    steps:
      - name: Check if all status checks have passed
        run: |
          if [[ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]]; then
            echo "Not on main branch. Skipping status checks."
            exit 0
          fi
          # Check if required status checks are passed
          if [[ "$(git log -1 --pretty=%B)" =~ "skip status checks" ]]; then
            echo "Status checks are skipped based on commit message."
            exit 0
          fi
          echo "All status checks passed."
